/**
 * Reseed script — clears all Setmore reviews and re-inserts them with correct dates.
 * Run with: npx tsx prisma/reseed-reviews-with-dates.ts
 *
 * Reference date: 2026-03-12 (the day the reviews were copied from Setmore)
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const REF = new Date('2026-03-12T12:00:00Z');
const d = (days: number) => { const x = new Date(REF); x.setDate(x.getDate() - days); return x; };
const w = (weeks: number) => d(weeks * 7);
const m = (months: number) => { const x = new Date(REF); x.setMonth(x.getMonth() - months); return x; };
const y = (years: number) => { const x = new Date(REF); x.setFullYear(x.getFullYear() - years); return x; };

const REVIEWS: { name: string; text: string; date: Date }[] = [
    { name: 'Dee', date: d(2), text: 'I had such a great experience with Jojo! She accommodated me last minute the same day, which I really appreciated. From the moment I walked in she was super welcoming and the whole vibe was great. You can truly tell how passionate she is about her work. I came in after a previous bad haircut experience and she completely brought my hair back to life. She listened to exactly what I wanted and delivered perfectly. I left feeling beautiful, confident, and refreshed. I highly recommend Jojo to anyone looking for a talented stylist who really cares about her clients!' },
    { name: 'Diana Escatel', date: d(3), text: 'Me encantó el servicio. Desde que llegué me atendieron súper bien y fue muy cuidadosa y detallista, se tomó su tiempo para que todo quedara perfecto. Mis uñas quedaron hermosas, justo como las quería. Definitivamente volveré y la recomiendo mucho si buscan un buen servicio de uñas 🎀💗💗' },
    { name: 'Martinez', date: d(3), text: "She does an amazing job every time I go .. I always recommend her with my friends/ coworkers she does all types of services don't hesitate on booking with her you'll love her work and her such a sweet kind person 💕" },
    { name: 'Michille Grosse', date: d(3), text: "She is a true professional! She takes her time and doesn't rush the nails,and they looked just like my inspo and she even added some other things, to it when I asked! Definitely will go again!" },
    { name: 'Kaitlyn Leiva', date: d(4), text: "Good vibes, good conversation, and amazing services. I've gone to Jojo for my nails and my hair. Firstly, the nails have amazing retention and always get me compliments. Secondly, just her cutting my hair has given me so much confidence. I actually style my hair now and do so much with it! Also side note: I think I'm her most indecisive client and she's always so amazing with changing designs on the fly or waiting until I'm at my appointment for the inspo. Love her because it might be last minute but she's always going to eat down. So if you were thinking about booking, do it. She's definitely worth it. 🩷" },
    { name: 'Guadalupe Lopez', date: w(2), text: 'I went to this nail salon and Jojany was amazing! Totally appreciate her my nails came out amazing and I love them ! Thank you Jojany' },
    { name: 'Yesenia Sanchez', date: w(2), text: 'Jojany was amazing! She was so kind, made me feel welcomed, and did a great job on my hair! I would recommend getting your hair done with her! Thank you so much!' },
    { name: 'Kaylee', date: w(2), text: "First off the vibe.. OMG it's super cute inside and jojo has this big mirror set up in front of where she works so you can really see everything. Love that! Jojo is super easy to talk to, not a dull awkward moment. She transformed my year outgrown blonde to this beautiful Barbie beach girl look. I loveeee it!! My hair hasn't felt this healthy in a long time AND it was dyed it. I strongly recommend! It was such a great experience." },
    { name: 'Janet D', date: w(2), text: "Jojany is a total vibe!!! She never disappoints and I'm beyond happy with my nail set!! Exactly what I wanted and needed!!!" },
    { name: 'Gloria Jimenez', date: w(2), text: 'Amazing service and amazing person always goes above and beyond. 💞' },
    { name: 'Daniela Castillo', date: w(3), text: 'Haces un excelente trabajo quedé muy satisfecha . Aparte eres muy carismática , haces sentir un ambiente muy cómodo y agradable. Gracias por tu buena atención 😊😊😊' },
    { name: 'Olivia Tate', date: w(3), text: "Jojany was amazing! Definitely exceeded my expectations, she was so chill and sweet! 10/10 services and personality ✨💕 Would definitely recommend to anyone who's looking for a nail tech/hairstylist that cares about her clients! 😇" },
    { name: 'Maryjane Munoz', date: m(1), text: "Loved every minute with jojo!! Amazing work amazing energy and I can gladly call her a friend now !! 1000% would recommend, had such a great experience that I had to book an appointment for my nails and my sons next haircut !!" },
    { name: 'Anel Brito Ramírez', date: m(1), text: 'Excelente servicio, súper recomendada. 10 de 10.✨💕⭐️⭐️⭐️⭐️⭐️' },
    { name: 'Yajaira Domínguez', date: m(1), text: 'Went to get a layered cut and let me say how perfect it is!! layered haircuts are always a hit or miss but She completely understood what I wanted' },
    { name: 'Fatima Magana', date: m(1), text: 'A gem! Super sweet and accommodating from the start, she made the schedule work so I could get in to see her. When we talked about my hair goals she was super knowledgeable and honest. I left with a haircut I loved and a beautiful blow out. It can be hard to find a skilled stylist who truly loves her job AND has such accessible pricing. This is her! Book that appointment!' },
    { name: 'Miriah Krahn', date: m(3), text: 'Amazing, amazing, amazing! I enjoyed every moment of it and my nails looked amazing!' },
    { name: 'Yadira Ledesma', date: m(3), text: 'Absolutely loved my hair cut and haircut. Loved that she was able to get in me at such a short notice. Will definitely be going back to her. Thank you 😊' },
    { name: 'Cheyanne Jauregui', date: m(3), text: "She did an AMAZING 🤩 job. I asked for an updo and glam and she delivered. I usually hate the way people color my eyebrows but she did SO GOOD. Not only is her skill set incredible, she is so sociable! We had great convos and it was enjoyable and very comfortable. She answered my questions and when I asked about what she used on my eyebrows she gave me reccs. Will def be going back for more services! She is 100% worth it. If you're on board, bite the bullet and book her u won't regret. Looking for a complex updo? She's got it. Ball makeup? 💄 She's got it. Def rec female Marines to book her for your makeup and updos for the ball." },
    { name: 'Hope Holt', date: m(3), text: "Jojany did an absolutely amazing job on my hair and makeup for the Marine Ball! She made me feel so beautiful and confident, and her work held up perfectly all night. On top of that, she was kind enough to fit me in last minute, which I appreciated more than I can say. I couldn't have asked for a better experience — highly recommend!" },
    { name: 'Janeya Avelar', date: m(4), text: "Absolutely loved my hair and makeup for my husband's ball. She is amazing and so sweet love her aura and the vibes she brings. Highly recommend her and will be booking with her for any occasion." },
    { name: 'Kimberly', date: m(4), text: 'Got my nails done with Jojo absolutely love them, great service with her' },
    { name: 'Maria Bonilla', date: m(4), text: 'Jojo did a phenomenal job doing my new hair transformation I got a beautiful balayage hair color !!! Im so obsessed and happy with it !😩' },
    { name: 'Jazmin Zamora', date: m(4), text: "I'm obsessed with my hair cut. I've gotten numerous compliments and I felt so pretty walking out of the salon with my hair. If you're looking for a local stylist who truly listens to what you want and goes above and beyond to make sure you're happy this is the place. I'll definitely be coming back." },
    { name: 'Gloria', date: m(4), text: "Thank you Jojany. I absolutely love her work. She has cut, colored and layered my hair several times now. I've gotten so many compliments on my hair. Just today she did my toes. I got a French manicure on them. I love that too. No one was ever able to do a Frenchie on my toes before. If you looking for a hair stylist or nail tech go to her. You won't be disappointed." },
    { name: 'Larissa', date: m(4), text: "She's very very kind and beautiful she did so good on my hair I asked her to keep as much as she could because me hair was supper dead it still looks so long I love it!!" },
    { name: 'Hailey Love', date: m(5), text: 'I loved working with Jojany! She made me feel so comfortable and did an amazing job on my 3-in-1 appointment for acrylic manicure, gel pedicure, and brazilian wax. I definitely recommend!' },
    { name: 'Jennifer Pope', date: m(5), text: "Jojo was absolutely fabulous and gave the best nail service. This was my first time with her and I will definitely be a regular client now and recommending her to all my friends! I got a gel x set and she was very gentle and took time to adequately prep my nails and applied the set without any bubbles or over flow into the nails like other artist that have done this one me so I know these beauties are gonna be stuck on for weeks. She took my inspo and gave me something even better! Great vibes and even better service!" },
    { name: 'Lannie Presley', date: m(5), text: 'Quick booking and she is very friendly! Loved my cut/layers!' },
    { name: 'Lilith Jane', date: m(5), text: "Jojany is the BEST!! I've been looking for a nail tech in vista for over a year and can't believe I didn't find her sooner! Her precision to detail on nail shape, length, and design is incredible!! She even went above and beyond actually looking at my nails before starting the service to gauge how much prep to do. When curing the gel, I said it would get hot and she immediately removed my nail to let it cool down. If you want a nail tech that ACTUALLY cares about you as a client and the integrity of your nails, book with Jojany!!! I wish i could rate her 10 stars!" },
    { name: 'Mari-Irene', date: m(5), text: 'Loved my facial 💆🏻‍♀️ she was super gentle & sweet 😊 I will definitely go back again for her services 😇' },
    { name: 'Yurivia', date: m(5), text: "She's super sweet and she did particial highlights on my hair but she did super good and I loved the outcome she did! I highly recommend Her!" },
    { name: 'Liz', date: m(5), text: "Amazing customer service I felt so comfortable from the moment I walked in and my hair cut was exactly what I asked for. Def recommend she's great" },
    { name: 'Emily Mendez', date: m(5), text: 'made me feel super comfortable and welcome in her chair 💕 in love with my new fresh look' },
    { name: 'Eva', date: m(5), text: 'I loved my hair after that amazing Brazilian blowout! Thank you for the amazing service. I will definitely be coming back!' },
    { name: 'Sujey', date: m(5), text: "After looking for the right place to get a haircut, I have finally found it. I found Jojany through a facebook post in a group and after looking her work, I knew I needed a haircut with her. I get nervous getting a haircut, especially since I haven't had a good experience in the past, but with Jojany, she made the experience fun. I felt comfortable going there and I have found a new place that I'll always be going to." },
    { name: 'Jeshua Escalera', date: m(6), text: 'Gracias!!' },
    { name: 'Jeshua Escalera', date: m(6), text: 'Thank you Jojo I knew it would be well worth the drive ever since I saw your talent on Fb and Instagram. Love my results! My hair came out so so good & elegant. Jojo is a perfectionist, takes her time and we can testify loves what she does. Thank you Jojo, this was my birthday gift I needed for a very long time. You are..simply the best!!!' },
    { name: 'Jazmin Keenan', date: m(6), text: 'I really enjoyed my experience Jojany is really great and she made me feel welcome and made my hair look amazing!! i definitely recommend!!!' },
    { name: 'Evelyn Marez', date: m(6), text: 'Jojo did so good on my hair! 10/10!!' },
    { name: 'Ana G Valdivia Valadez', date: m(6), text: 'Tuvimos muy buena comunicación eya en verdad ama su trabajo y es muy buena en lo que hace ❤️' },
    { name: 'Ella Jurasko', date: m(6), text: 'amazing service, atmosphere, and results!! I love how my hair turned out, its the blackest black ever with the most beautiful layers!! I 10000% recommend this wonderful lady!! ❤️❤️' },
    { name: 'Diana S Ortiz', date: m(6), text: "Definitely book with Jojany for any services you need done! She did an amazing job with my hair, she made it look so much better than what I asked for. She made me feel so comfortable as well while getting my hair done, the hours flew on by. I will definitely be going to her for everything that I need done now! Don't wait and book with her !!" },
    { name: 'Amy Anderson', date: m(6), text: "This is my second time booking with her and she's officially my go-to hairstylist now! 💕 She's super sweet, so easy to talk to, and always makes you feel welcome. Never a boring moment during the appointment, and her work is soooo amazing 🥰 She did such a beautiful job on both my hair and my sister's! Plus, her prices are totally affordable, which is a huge bonus. Can't recommend her enough! 💇🏽‍♀️✨" },
    { name: 'Karina A', date: m(6), text: "I'm obsessed with my nails! 💅 She absolutely killed it — super clean work, perfect shape, and exactly what I needed. She's so sweet and made me feel comfortable the whole time. Definitely my new go-to for nails! 💖" },
    { name: 'Maria Carson', date: m(6), text: "I've been twice now and gave Johany a few inspo ideas and told her freestyle the rest! She blew my away both times she such an artist and she's my fav nail tech ever!!" },
    { name: 'Happy Client', date: m(6), text: "she was the sweetest ever and her prices are the best better than any other nail person I recommend her and shes a baddiee and her work is amazing I'm gonna continue getting my nails done from her and u should get urs done from her to the best of the best!!" },
    { name: 'Adri Sánchez', date: m(6), text: 'You are the best, Thank you for leaving my hair beautiful and my nails so pretty, you have magical hands, thank you. 😍💖💖💖' },
    { name: 'Rosita M', date: m(7), text: "My girl was AMAZING! I booked Jojany for both makeup and hair — and let me tell you, I was a little hesitant at first since I found her on Facebook Marketplace. But from the moment we met, she blew me away with her professionalism and warm personality. Even though it was our first time meeting, she made me feel like I'd known her for years. So friendly, so engaged, and incredibly attentive! She walked me through every step of the process, communicating clearly before applying anything — and I LOVED that. I requested a soft glam look, and she nailed it! My makeup was flawless, and my hair was absolutely on point. I received so many compliments at the wedding I attended. Highly recommend her services — I can't wait to book with her again!" },
    { name: 'Nicole Hayward', date: m(7), text: 'I had my hair done on July 16 with JoJo and she did an AMAZING job!! I am from Michigan but I will be going back to her every time I come to California. Thank you soo much I LOVE 💜 it.' },
    { name: 'Daniella Bonilla', date: m(7), text: 'Amazing nail tech!!! had a pleasant experience with her, she gets to know her clients on another level. And literally copy and paste my inspo picture. 10 out of 10!!' },
    { name: 'Lexie Kondo', date: m(8), text: 'She did an amazing job and my hair came out exactly how I wanted. She is so nice and made my visit enjoyable!' },
    { name: 'Maria Bonilla', date: m(8), text: 'Best Stylist💅🏽 with good ethic skills great services enjoyed all my visits with her.' },
    { name: 'Stella', date: m(8), text: 'Had my red hair color removed and a beautiful brown with highlights done. It came out beautiful. Highly recommend. She is very talented. She takes her time to explain the process and in the end beautiful hair.' },
    { name: 'Kristen', date: m(8), text: "I literally never take the time to leave reviews. Well honestly I think I've done two in my lifetime. But WOW! I just have to take the time to say I have been highlighting my hair for 40 years. I have been to several very high end salons in those years. Recently I happened upon a Facebook post and decided to give Jojo a try. Boy am I ever glad I did! Not only is she very personable she literally gave me the best Malibu balayage I've ever had! The color is absolutely perfect and I could not be more impressed with her skills! My sister who is visiting went along with me and when she saw the finished product immediately booked an appointment to have her hair done before she leaves town! Do yourself a favor, take a leap of faith, trust me and have her color your hair! I promise you won't regret it!! She is a total rock star!" },
    { name: 'Sandy Navarrete', date: m(8), text: 'She is one of the sweetest and kindest and best hairdressers I know and will be definitely coming back to her and I highly recommend her' },
    { name: 'Kathryn Patten', date: m(8), text: "Went in needing a quick fix for a wedding I'm in next week. Left with exactly what I was expecting. Layers with curtain bangs. I haven't had layers in years so I was a bit nervous, my hair feels weightless and so much healthier. Will be returning for other services. The atmosphere, customer service and quality is top notch. Highly recommend!" },
    { name: 'Noemy Garcia', date: m(8), text: 'Loved her services and dedication to listening to what I wanted for my hair service. Very sweet and easy to get along with definitely will be back !!🫶🏼' },
    { name: 'Jadyn', date: m(8), text: "I absolutely loveddddd my haircut and style. I got exactly what I wanted and it's perfect." },
    { name: 'Ana', date: m(8), text: "Jojo does an amazing job cutting my hair! I started going to her back when she was cutting hair in her garage, and even then, I was impressed. It's been almost two years since my last visit, and I recently returned for a haircut—and I'm absolutely in love with it! She truly listens to what you want and goes above and beyond to deliver a look that suits you perfectly. The atmosphere with Jojo is safe, comfortable, and welcoming. She's not only incredibly talented, but also so sweet and professional. I'm so glad I've found my go-to hairstylist!" },
    { name: 'Stephanie', date: m(8), text: "10/10 loved the experience and friendly environment! I absolutely loved my hair didn't damage nor give me a color I didn't want!🫶🏻" },
    { name: 'Jennifer Talamantes', date: m(8), text: "She was the second person to do my hair professionally and can 110% recommend her to others! She was so sweet and definitely gave me what I wanted for my hair service. great communication and overall her service is amazing! You are missing out if you haven't booked yet ! I loved my outcome ☺️" },
    { name: 'Diana', date: m(8), text: "The best in the industry from Nails, Hair, to make up, let me just say that I've found my all in one tech, I highly recommend her to anyone that needs any services done. Stop contemplating and book, you won't regret it I promise you!!" },
    { name: 'Joselyn Ortiz', date: m(8), text: "I would definitely recommend. it's was really clean and the service was amazing she was really sweet and very respectful. Thank you so much for everything." },
    { name: 'Marfy Cruz', date: m(8), text: 'Quick response and worked with my schedule, great service and loved my highlights. She met my expectations' },
    { name: 'Angelina', date: m(8), text: 'I came into the salon wanting a haircut and blowout and left feeling amazing. Jojany did an amazing job and transformed my hair. I highly recommend her and will definitely be coming back.' },
    { name: 'Denise Tapia', date: m(8), text: 'THE BEST HAIRCUT!! She always does such a good job. She follows my inspiration and she can make my hair look like the pictures!!! In love with it!' },
    { name: 'Jazzy', date: m(8), text: "I had such a great experience getting my hair cut and dyed. She was not only super friendly and welcoming, but also really listened to what I wanted and made sure everything came out exactly how I pictured it—if not better. The color came out beautiful and vibrant, and the cut feels fresh and flattering. I left the salon feeling so confident and happy. You can tell she truly cares about her clients and takes pride in her work. Highly recommend booking with her you won't regret it!" },
    { name: 'Evelyn M', date: m(8), text: 'Jojany did an amazing job with my hair, she is very sweet and welcoming! Highly recommend her!!' },
    { name: 'Vanessa Carvajal', date: m(8), text: 'I love my nails so much she did a good job definitely recommend she was able to fit me in last minute I will definitely be going back to her' },
    { name: 'Cheyenne Smith', date: m(8), text: 'this girl is incredible!! i had the best overall experience while being in her chair! wonderful hair cut and an even better conversation! she does it all! do yourself a favor and book with her asap :))' },
    { name: 'Mayra L', date: m(9), text: 'Jojo did an amazing job . She did exactly what I wanted . She made me feel welcomed and has excellent customer service.' },
    { name: 'Jesselyn Hanson', date: m(9), text: "Jojany was super sweet it was my first time meeting her, I haven't done my nails in a few years but I had some events coming up that I wanted to get them done. I sent her a few different inspiration photos and also told her she can free hand whatever she wanted to do, she took my ideas and did a great job and was very thorough. I will be making another appointment and also for my younger daughter" },
    { name: 'Hailey', date: m(9), text: "Jojany was an absolute pleasure! From the moment I walked in she was so nice and easy to talk to! She listened to my haircut requests carefully, as I've been trying to grow my hair out and didn't want to lose my length, and she executed it perfectly! She's truly amazing and I can't wait to come back for more services ✨✨ Definitely check her out!" },
    { name: 'Natalia', date: m(9), text: 'Loved the haircut, everything went smooth and it was definitely a good time. Jojo was very sweet and gentle, when it came to my hair, never had someone be so caring with my hair! Thank you again' },
    { name: 'Jacky', date: m(9), text: 'It was my first time coming to her and it was an her services are just wonderful and she takes her time and I loved my outcome to my haircut, as well my nails ,toes and she haves so much patience highly recommend her. Will definitely be coming back ✨💗' },
    { name: 'Karina', date: m(9), text: "I had such a great experience! She did my hair and my mom's nails, and we both left feeling so happy and confident. Not only is she incredibly talented at what she does, but she's also super sweet and made us feel so comfortable the whole time. Her attention to detail and care for her clients really shows. Great service, great vibe we will definitely be coming back! 💇‍♀️💅❤️" },
    { name: 'Esmeralda Jimenez', date: m(9), text: "I had a great experience. I didn't have anything in mind as to what I wanted and was pleased to let her do a design. They came out amazing and the great thing was that she was super easy to talk to!!!" },
    { name: 'Lucero Vargas', date: m(9), text: 'Loved my experience she replied fast when I messaged her and was able to book me the same day. Loved her positivity and made my experience unique by sharing stories, also my haircut and blow out made me feel amazing I absolutely loved it. 10/10' },
    { name: 'Yahiara', date: m(9), text: "I LOVED my haircut! Listened to what I asked for and did exactly that. Ive never been so happy with a haircut before💕 Definitely will be coming back. Super nice and amazing service!" },
    { name: 'Mireya', date: m(9), text: "Jojany did amazing on my hair and makeup and she's so cool and sweet!! Will for sure book with her again 🩷" },
    { name: 'Febe Griffin', date: m(9), text: "I loved my haircut! I'm definitely coming back:)" },
    { name: 'Amaris Mora', date: m(9), text: 'First time going with Jojany and I loveeeeed my haircut and the way she styled it! Also she is super nice and makes you feel welcomed 💖 will definitely keep trusting my hair to her ✨' },
    { name: 'Rosa Montanez', date: m(9), text: 'I had a great experience love my make up and hair' },
    { name: 'Aileen', date: m(9), text: 'I absolutely loved my nails done by Jojany! She was super friendly and patient and did exactly what I asked for. Definitely recommend booking with her!☺️' },
    { name: 'Anisa', date: m(9), text: 'Jojo was absolutely amazing! From the minute I walked in she was so welcoming an we talked an laughed the whole time .she made me feel so comfortable, my nails omg my nails i love them is an understatement she had a vision that came to life from what I told her I liked an she gave me the best nails ever Im so excited we crossed paths an I will definitely be going back to her .. 10 stars' },
    { name: 'Sarai Gonzalez', date: m(9), text: "I loved how patient, sweet, and talkative to she was while doing my nails! I didn't even realize the time went by so quick lol. I sent her my inspo and she made it possible ☺️ Definitely will be coming back to her !" },
    { name: 'Jess Ponce', date: m(9), text: "She's the best ! Did exactly what I wanted , most definitely the only person I'll trust with my hair ! ☺️" },
    { name: 'Melissa Diaz', date: m(9), text: "I had a great experience at my appointment, her personality is very welcoming and did a great job on my hair considering that I had went in with a different color shades , she definitely touched those up for me and left with silky soft hair , would recommend to others fersure" },
    { name: 'Kaitlyn', date: m(9), text: 'I absolutely LOVED the service i recieved. My nails are flawless, conversation was amazing and the look of the salon itself was perfect!' },
    { name: 'Aylin', date: m(9), text: 'Loved going to Jojo for my nails. She was very sweet. Definitely will be back. 10/10 recommend!' },
    { name: 'Emma Montanez', date: m(9), text: 'Amazing job at my makeup and hair. She was very detailed in making sure everything came out and that I enjoyed the look. I explained to her my ideas for they I was looking for and she made it come to life. She is a great listener and very considerate of your ideas. HIGH RECOMMENDATION!!!' },
    { name: 'Alyssa Hicks', date: m(9), text: "Jojany went above and beyond, not only did she make my hair come to life again she took her time and explained everything in details ! I would 100% recommend her if you need anything hair related she's truly the best !!!" },
    { name: 'Meredith Weissberg', date: m(9), text: 'I absolutely love getting my nails done by her! My set came out better than the original picture!' },
    { name: 'America', date: m(9), text: "Jojo was super sweet! She makes you feel comfortable and she's super funny too! On top of that, her work was amazing. She left my hair looking so shiny and overall brand new which is what I needed. 10/10 recommended!" },
    { name: 'Amalia', date: m(9), text: "Jojany did an amazing job! I loved it from the moment I stepped in and met her she has been nothing but sweet and professional! She did amazing with consulting on how I wanted my haircut especially with my hair being curly, she brought it back life! I am definitely coming back again in a few weeks for a hair color service! Definitely recommend jojany!" },
    { name: 'Ashley', date: m(9), text: 'She was truly amazing. First time meeting her and she made me feel so comfortable and welcoming. Did all hair dye and was very satisfied my hair feels amazing and definitely will be coming back.' },
    { name: 'Ashley Barrera', date: m(9), text: "Jojany gave me a perfect haircut and treatment for hair loss. She's so easy to talk to and understands exactly what you want. I was there for about 2 hours and time went flying. Lastly, she works around your schedule and tries her best to make sure you get well taken care of. I will definitely be back for color soon!" },
    { name: 'Tania Aguirre', date: m(9), text: 'Recomiendo el lugar por mi experiencia la verdad me gustó mucho su trabajo, muy profesional por su parte ! Me encantó el look' },
    { name: 'Sharon', date: m(10), text: 'Literally the most chillest nail tech! Jojany you are amazing! We literally talked and laughed all the way thru the appointment it was so fun and such a good experience! Will definitely be coming back! Thank you so much! 🫶' },
    { name: 'Alejandra', date: m(10), text: 'Jojoany did an amazing job on my hair. Made me feel very welcomed the second I came in such an easy girl to talk too, will definitely be coming back!!' },
    { name: 'Emily', date: m(10), text: "I came in with years of box dye, and I came out with a perfect honey blonde. Atmosphere is so comforting. Talked me through the process and checked in constantly. Went from dry damaged hair to golden healthy. ✨ I've found my Cali hair girl 🫶🏻" },
    { name: 'Jeni', date: m(10), text: "Honestly jojo made me feel so welcomed and comfortable not only that her work is the best she really has a passion and patience for what she does and I appreciate it so much I love my hair definitely recommend for anyone ‼️💖" },
    { name: 'Gloria J', date: m(10), text: 'Jojany has a great personality. She understood my concept for my haircut. I fell in love with my hair. It was exactly what I wanted. Thank you for listening and making me feel welcomed. ❤️' },
    { name: 'Isabel', date: m(10), text: 'Jojo, what can I say. My first time with you was amazing. I can see you are passionate with what you do and I love it! Thank you for being honest and upfront before I chose the hair color that I wanted. #passionate #friendly #honestly' },
    { name: 'Mona Lysa Vasquez', date: m(10), text: "I had an amazing experience at my appointment! She's was so sweet and understanding, knew exactly how I wanted my hair, 10/10 recommend her services! BOOK NOW 🤍" },
    { name: 'Ahtziri', date: m(10), text: 'Had an amazing experience.loved how my hair came out plus layers 10/10 service and over all super friendly' },
    { name: 'Priscilla Lavender', date: m(10), text: "Today I had my first appointment and let me tell you I was soo happy I found an amazing and friendly hairstylist. The conversation was just great and felt like we knew each other. She gives the best advice on color before booking and listens to all your wishes on how you want your cut!!! My haircute and color came out amazing that I got soo many compliments. So dont hesitate to book with her!!!" },
    { name: 'Dykesha Chavers', date: m(10), text: "Jojany was amazing! She did my nails and my daughter's nails and they look amazing. She was so personable and professional. I look forward to going back 😊" },
    { name: 'Fatima M', date: m(11), text: "She was absolutely a pleasure to be around! Super sweet and a nice person all around. Made me feel comfortable from the second I got there. Was able to work around my schedule which is A MAJOR PLUS being a military spouse. My husband's schedule is so crazy and weird I was grateful I was finally able to get my hair done thanks to her! Sad I can't add photos to show how great she did! I definitely recommend, great service & a great gal! Thank you again for the great experience🤍" },
    { name: 'Katelyn Perez', date: m(11), text: 'She is the first one to get my nails the way I wanted them with a great pricing for them I highly recommend going through her if you need to get your nails done 💅 and so she is so kind!!' },
    { name: 'Sharon Corona', date: m(11), text: 'Jojany is amazing! So friendly and easy to chat with! I got an acrylic fill with some nail designs and she absolutely nailed it! Highly recommend !!' },
    { name: 'Nikki Zuchowsky', date: m(11), text: '10/10 my favorite Nail Tech that I have been to since being here! She was so friendly and polite, makes the environment so comfortable and enjoyable!' },
    { name: 'Jaye Lynn', date: m(11), text: "i had an AMAZING experience with jojo. i brought my little with me and she was so accommodating!! my nails looks stunning! and i will definitely be booking other services with her. 10/10 all around i won't go to anyone else after booking with her" },
    { name: 'Angelica', date: y(1), text: 'Jojany accepted my appointment last minute and did wonderfully!! Gave me exactly what I wanted for color and fixed a previous botched hair cut!!' },
    { name: 'Denise Tapia', date: y(1), text: 'Not sure if my other review posted, but I had such amazing service today. My hair came out so beautiful. My cut and blowout was really affordable and Jojany did it amazing. Would recommend!!' },
    { name: 'Denise Tapia', date: y(1), text: 'Went here today and I had amazing service! My hair came out beautiful and shiny. Got exactly what I asked for and Jojany was super kind and sweet. Would recommend this place!!' },
    { name: 'Danna Waddington', date: y(1), text: "I am happy with the services done by Jojany, she did a beautiful job at doing my makeup and not to mention she has such a light hand with makeup and hair, I was surprised when she handed me the mirror because it was to look at my hair already done. I lover her energy and was easy to talk to." },
    { name: 'Auie Gunn', date: y(1), text: "I had the absolute pleasure of working with Jolany and I couldn't be happier with the results! She made me feel so confident and radiant for my special event. The makeup was flawless and complemented my dress perfectly. It lasted all night without smudging or fading, even with all the dancing and photos! She were also incredibly professional, friendly, and attentive to what I wanted. I highly recommend her for any occasion—you won't be disappointed." },
    { name: 'Hirely Villalobos', date: y(1), text: "I had an amazing experience with Jojany ! She did an incredible job on my hair, and I couldn't be happier with the result. Not only was the quality of her work top-notch, but her service was exceptional. She made me feel comfortable, listened to exactly what I wanted, and went above and beyond to ensure I was happy with my look. I highly recommend her to anyone looking for a professional, talented, and personable hairstylist. I'll definitely be returning!!" },
];

async function main() {
    console.log('Clearing existing Setmore reviews...');
    const { count } = await prisma.review.deleteMany({ where: { source: 'setmore' } });
    console.log(`Deleted ${count} reviews. Re-inserting with correct dates...`);

    for (const r of REVIEWS) {
        await prisma.review.create({
            data: {
                rating: 5,
                text: r.text,
                source: 'setmore',
                authorName: r.name,
                createdAt: r.date,
            },
        });
    }

    console.log(`✅ Inserted ${REVIEWS.length} reviews with correct dates.`);
    await prisma.$disconnect();
}

main().catch(e => { console.error(e); process.exit(1); });
